site/app/routes.php
<?php

// route for language [en,de]
Route::get('language/{lang}', array(
        'as'   => 'language.select',
        'uses' => 'LanguageController@select'
    )
);
Route::resource('lang', 'LanguageController');
Route::resource('chat', 'ChatController');
Route::post('ajax/process', array(
    'as'   => 'process',
    'uses' => 'ChatController@process'
));
Route::post('process', 'ChatController@process');
// resources
// path to users controller : index, show, edit, create
Route::resource('users', 'UsersController');
// path to session controller : index(login page), show(choose application page), create (register page)
Route::resource('sessions', 'SessionsController');
Route::get('new-user-login', 'SessionsController@newUserLogin');
Route::get('forgot-password', 'SessionsController@getForgotPassword');
Route::post('post-forgot-password', 'SessionsController@postForgotPassword');
Route::get('recover-password/{token}', 'SessionsController@recoverPassword');
Route::post('post-recover-password/{token}', 'SessionsController@postRecoverPassword');
Route::resource('exporter', 'ExporterController');

// logout
Route::any('logout', 'SessionsController@destroy');

// routes for register / login /
Route::any('/', 'SessionsController@index');
Route::any('login', 'SessionsController@index');


Route::any('registerUser', 'SessionsController@registerUser');
Route::any('activation', 'SessionsController@activation');
Route::any('accept-user/{id}', 'SessionsController@acceptUser');
Route::any('decline-user/{id}', 'SessionsController@declineUser');
Route::any('employees-list/{id}', 'SessionsController@employeesList');
Route::any('check_login', 'SessionsController@check_login');

//  ajax for headquarters details
Route::get('ajax/viewHeadquarters/{id}', array(
    'as'   => 'id',
    'uses' => 'SessionsController@viewHeadquarters'
));
Route::get('ajax/viewHeadquarterDetails/{id}', array(
    'as'   => 'id',
    'uses' => 'SessionsController@viewHeadquarterDetails'
));

Route::post('/checkCompanyEmail', ['uses' => 'SessionsController@checkCompanyEmail']);
Route::post('/checkHeadquarterEmail', ['uses' => 'SessionsController@checkHeadquarterEmail']);
Route::post('/checkUserEmail', ['uses' => 'SessionsController@checkUserEmail']);

// if user logged in front
Route::group(array('before' => 'auth'), function () {

    Route::resource('invoice', 'InvoiceController');
    // path to members controller : index, show, edit, create
    Route::resource('members', 'MembersController');
    Route::get('members/create_adm/{id}', array(
        'as'   => 'id',
        'uses' => 'MembersController@create_adm'));
    Route::get('members/delete_adm/{id}', array(
        'as'   => 'id',
        'uses' => 'MembersController@delete_adm'));
    Route::get('members/approve/{id}', array(
        'as'   => 'id',
        'uses' => 'UsersController@approve'));
    Route::get('members/admin-approve/{id}', array(
        'as'   => 'id',
        'uses' => 'UsersController@admin_approve'));
    Route::get('members/block/{id}', array(
        'as'   => 'id',
        'uses' => 'UsersController@block'));
    Route::get('members/admin-block/{id}', array(
        'as'   => 'id',
        'uses' => 'UsersController@admin_block'));
    Route::get('members/change_group/{id}', array(
        'as'   => 'id',
        'uses' => 'UsersController@change_group'));
    Route::get('members/change_group_by_admin/{id}', array(
        'as'   => 'id',
        'uses' => 'UsersController@change_group_by_admin'));
    Route::get('profile', 'UsersController@profile');

    // path to session affiliates : index, show, edit, create
    Route::resource('affiliates', 'AffiliationController');
    Route::any('affiliates.accept', 'AffiliationController@accept');

    // path to session company : index, show, edit, create
    Route::resource('company', 'CompanyController');
    Route::get('/companyTab/{tab}', 'CompanyController@redirectFromDasboard');
    Route::get('/companyTab/{tab}/add-for/{add}', 'CompanyController@redirectFromDasboardAddNew');
    Route::resource('acompany', 'CompanyAdmController');
    Route::get('acompany/delete_adm/{id}', array(
        'as'   => 'id',
        'uses' => 'CompanyAdmController@delete_adm'));
    Route::get('approve-company/{id}', array(
        'as'   => 'id',
        'uses' => 'CompanyAdmController@approveCompany'));
    Route::get('block-company/{id}', array(
        'as'   => 'id',
        'uses' => 'CompanyAdmController@blockCompany'));

    // path to session headquarters : index, show, edit, create
    Route::resource('headquarters', 'HeadquartersController');
    Route::get('headquarters/create_adm/{id}', array(
        'as'   => 'id',
        'uses' => 'HeadquartersController@create_adm'));

    Route::get('headquarters/delete_adm/{id}', array(
        'as'   => 'id',
        'uses' => 'HeadquartersController@delete_adm'));
    Route::get('headquarters/make_main/{id}', array(
        'as'   => 'id',
        'uses' => 'HeadquartersController@make_main'));
    Route::get('headquarters/admin_make_main/{id}', array(
        'as'   => 'id',
        'uses' => 'HeadquartersController@admin_make_main'));


    // path to projects controller : index, show, edit, create
    Route::resource('projects', 'ProjectsController');
    Route::any('pack', 'ProjectsController@packages');
    // add / remove users per project
    Route::any('projects_add_users', 'ProjectsController@projects_add_users');

    Route::get('projects_remove_users/{id}', array(
        'as'   => 'id',
        'uses' => 'ProjectsController@projects_remove_users'));

    //purchases
    Route::get('/purchases', [
      'uses' => 'PurchasesController@getCheckout',
      'as' => 'purchases'
    ]);

    Route::post('/purchases/{id}', [
      'uses' => 'PurchasesController@postCheckout',
      'as' => 'purchases'
    ]);

    // project - extend period
    Route::post('/projects/update_due_date', ['uses' => 'ProjectsController@update_due_date']);

    // project - upload attachment
    Route::any('upload', 'ProjectsController@upload_file');
    // project - update tasks
    Route::post('select', array('as'   => 'ajax.update_project_task',
                                'uses' => 'ProjectsController@update_project_task'));

    Route::get('modal_dialog_edit_task_project/{id_ms_task}/{id_project}', array(
        'as'   => 'id',
        'uses' => 'ProjectsController@modal_dialog_edit_task_project'));
    Route::get('modal_dialog_add_task_project/{id_module_structure}/{id_industry}/{id_project}', array(
        'as'   => 'modal_dialog_add_task_project',
        'uses' => 'ProjectsController@modal_dialog_add_task_project'));
    Route::get('modal_dialog_add_task_new_project/{id_module_structure}/{id_industry}/{id_project}', array(
        'as'   => 'modal_dialog_add_task_new_project',
        'uses' => 'ProjectsController@modal_dialog_add_task_new_project'));
    Route::get('modal_dialog_edit_module_project/{id_module_structure}', array(
        'as'   => 'modal_dialog_edit_module_project',
        'uses' => 'ProjectsController@modal_dialog_edit_module_project'));


    Route::post('set_order_projects', array('as'   => 'ajax.set_order_projects',
                                            'uses' => 'ProjectsController@set_order_projects'));
    Route::post('set_order_front_task', array('as'   => 'ajax.set_order_front_task',
                                              'uses' => 'ProjectsController@set_order_front_task'));

    Route::get('/download_project_pdf/{bar}', array(
        'as'   => 'bar',
        'uses' => 'ProjectsController@download_project_pdf'
    ));
    Route::get('download_project_word/{bar}', 'ProjectsController@download_project_word');
    Route::get('download_word_html/{bar}', 'ProjectsController@download_word_html');

    Route::get('download_project_excel/{bar}', 'ProjectsController@download_project_excel');
    Route::get('download_excel_html/{bar}', 'ProjectsController@download_excel_html');

    Route::get('download_software_excel/{bar}', 'SoftwareController@download_software_excel');
    Route::get('download_software_excel/{bar}/{module}/{industry}/{project}', 'SoftwareController@download_software_excel');
    Route::get('download_software_excel/{bar}/{module}', 'SoftwareController@download_software_excel');
    Route::get('download_software_excel/{bar}/{module}/{industry}', 'SoftwareController@download_software_excel');
    Route::get('download_industry_excel/{bar}', 'IndustryController@download_industry_excel');

    // 'MaatwebsiteDemoController' = 'SoftwareController'
    Route::get('importExport', 'SoftwareController@importExport');
    Route::post('importExcel', 'SoftwareController@importExcel');

    Route::get('download_project_attachments/{bar}', 'ProjectsController@download_project_attachments');
    Route::get('download_software_attachments/{bar}', 'SoftwareController@download_software_attachments');
    Route::get('download_software_attachments/{bar}/{module}/{industry}/{project}', 'SoftwareController@download_software_attachments');
    Route::get('download_software_attachments/{bar}/{module}', 'SoftwareController@download_software_attachments');
    Route::get('download_software_attachments/{bar}/{module}/{industry}', 'SoftwareController@download_software_attachments');
    Route::get('download_industry_attachments/{bar}', 'IndustryController@download_industry_attachments');

    Route::any('upload_task', 'ProjectsController@projects_add_users');
    Route::any('add_new_task', 'ProjectsController@add_new_task');
    Route::any('add_new_task_empty_project', 'ProjectsController@add_new_task_empty_project');

    Route::any('remove_new_task', 'ProjectsController@remove_new_task');

    // handle module structure
    Route::post('delete_structure',
        array('as'   => 'ajax.delete_module_structure',
              'uses' => 'ProjectsController@delete_module_structure'));
    Route::post('edit_structure', array('as'   => 'ajax.edit_module_structure',

site/app/views/admin/headquarters/create.blade.php
{{ Form::open(['action'=>'HeadquartersController@store','id'=>'addHeadquarterForm']) }}

<div class="col-md-12">
    <div class="title_line">  {{trans('messages.act_add')}}   {{trans('messages.nav_headquarter')}}    {{trans('messages.l_for')}} {{  $company->name_company  }}  </div>
</div>
<div class="col-md-12">


    <div class="form-group has-feedback">
        {{ Form::text("name_headquarter[1]","",[ "placeholder"=>"Name Headquarter", "class"=>"form-control",'required' ]) }}
        {{ $errors->first("name_headquarter[1]","<div class='text-red'>:message</div>") }}
    </div>
    <div class="form-group has-feedback">
        {{ Form::text("telephone_headquarter[1]","",[ "placeholder"=>"Telephone Number", "class"=>"form-control" ]) }}
        {{ $errors->first("telephone_headquarter[1]","<div class='text-red'>:message</div>") }}
    </div>
    <div class="form-group has-feedback">
        {{ Form::email("email_headquarter[1]","",[ "placeholder"=>"Email", "class"=>"form-control", "required" ]) }}
        {{ $errors->first("email_headquarter[1]","<div class='text-red'>:message</div>") }}
    </div>
    <div class="form-group has-feedback">
        <div id="locationField">

            {{ Form::text("autocomplete[1]","",array( "placeholder"=>"Enter headquarter address",
            "class"=>"form-control", "id"=>"autocomplete1","onFocus"=>"initialize('1')","required")) }}
            {{ $errors->first("autocomplete[1]","<div class='text-red'>:message</div>") }}
        </div>
    </div>
    <table id="address1" class="table table-bordered table-responsive">
        <tr>
            <td>
                {{ Form::text("street[1]","",[ "placeholder"=>"Street name", "class"=>"form-control","id"=>"route1","required"]) }}
                {{ $errors->first("street[1]","<div class='text-red'>:message</div>") }}
            </td>

            <td>
                {{ Form::text("street_number[1]","",[ "placeholder"=>"Street number", "class"=>"form-control","id"=>"street_number1","required" ]) }}
                {{ $errors->first("street_number[1]","<div class='text-red'>:message</div>") }}
            </td>
        </tr>
        <tr>

            <td>
                {{ Form::text("city[1]","",[ "placeholder"=>"City", "class"=>"form-control","id"=>"locality1","required"]) }}
                {{ $errors->first("city[1]","<div class='text-red'>:message</div>") }}
            </td>
            <td>
                {{ Form::text("postal_code[1]","",[ "placeholder"=>"Postal Code", "class"=>"form-control","id"=>"postal_code1", "required"]) }}
                {{ $errors->first("postal_code[1]","<div class='text-red'>:message</div>") }}
            </td>
        </tr>
        <tr>

            <td colspan="2">
                {{ Form::text("state[1]","",[ "placeholder"=>"State", "class"=>"form-control","id"=>"administrative_area_level_11" ]) }}
                {{ $errors->first("state[1]","<div class='text-red'>:message</div>") }}
            </td>
        </tr>
        <tr>
            <td colspan="2">
                {{ Form::text("country[1]","",[ "placeholder"=>"Country", "class"=>"form-control","id"=>"country1","required"]) }}
                {{ $errors->first("country[1]","<div class='text-red'>:message</div>") }}
                {{ Form::hidden("latitude[1]","",[  "id"=>"latitude1" ]) }}
                {{ Form::hidden("longitude[1]","",[ "id"=>"longitude1" ]) }}
            </td>
        </tr>
    </table>


    <div class="input_fields_wrap">
    </div>

    {{ $errors->first("confirm_user",'<div class="text-green">:message</div>') }}
    {{ Form::hidden("id_company",$company->id_company) }}
    {{ Form::hidden("redirect_link",'acompany') }}

    <br>
</div>
<br>
<div class="col-md-6">
    <button type="submit" class='btn ls-light-blue-btn btn-block'>
        {{trans('messages.act_save')}}
    </button>
</div>
<div class="col-md-6">
    <button type="button" class='btn btn-danger btn-block' onclick="hide_modal_box()">
        {{trans('messages.act_cancel')}}
    </button>
</div>


{{ Form::close() }}

site/app/views/admin/headquarters/edit.blade.php
{{ Form::model($headquarter, ['method'=>'PATCH', 'route'=>['headquarters.update',$headquarter->id_headquarter]])}}

<div class="col-md-12">
    <div class="title_line">  {{trans('messages.act_edit')}}     {{ $headquarter->name_headquarter }}  </div>
</div>
<div class="col-md-12">
    <div class="form-group has-feedback">
        {{ Form::text("name_headquarter",$headquarter->name_headquarter,[ "placeholder"=>"Name Headquarter", "class"=>"form-control" ]) }}
        {{ $errors->first("name_headquarter","<div class='text-red'>:message</div>") }}
    </div>
    <div class="form-group has-feedback">
        <div id="locationField">
            {{ Form::text("autocomplete",$headquarter->address_string,array( "placeholder"=>"Enter headquarter address",
            "class"=>"form-control", "id"=>"autocomplete1","onFocus"=>"initialize('1')","required")) }}
            {{ $errors->first("autocomplete","<div class='text-red'>:message</div>") }}
        </div>
    </div>
    <table id="address1" class="table table-bordered table-responsive">
        <tr>
            <td>
                {{ Form::text("street",$headquarter->street,[ "placeholder"=>"Street name", "class"=>"form-control","id"=>"route1","required"]) }}
                {{ $errors->first("street","<div class='text-red'>:message</div>") }}
            </td>
            <td>
                {{ Form::text("street_number",$headquarter->street_nr,[ "placeholder"=>"Street number", "class"=>"form-control","id"=>"street_number1" ]) }}
                {{ $errors->first("street_number","<div class='text-red'>:message</div>") }}
            </td>
        </tr>
        <tr>
            <td>
                {{ Form::text("city",$headquarter->city,[ "placeholder"=>"City", "class"=>"form-control","id"=>"locality1","required"]) }}
                {{ $errors->first("city","<div class='text-red'>:message</div>") }}
            </td>
            <td>
                {{ Form::text("postal_code",$headquarter->postal_code,[ "placeholder"=>"Postal Code", "class"=>"form-control","id"=>"postal_code1"]) }}
                {{ $errors->first("postal_code","<div class='text-red'>:message</div>") }}
            </td>
        </tr>
        <tr>
            <td colspan="2">
                {{ Form::text("state",$headquarter->state,[ "placeholder"=>"State", "class"=>"form-control","id"=>"administrative_area_level_11" ]) }}
                {{ $errors->first("state","<div class='text-red'>:message</div>") }}
            </td>
        </tr>
        <tr>
            <td colspan="2">
                {{ Form::text("country",$headquarter->country,[ "placeholder"=>"Country", "class"=>"form-control","id"=>"country1","required"]) }}
                {{ $errors->first("country","<div class='text-red'>:message</div>") }}
                {{ Form::hidden("latitude",$headquarter->latitude,[  "id"=>"latitude1" ]) }}
                {{ Form::hidden("longitude",$headquarter->longitude,[ "id"=>"longitude1" ]) }}
            </td>
        </tr>
    </table>
    <div class="form-group has-feedback">
        {{ Form::text("telephone_headquarter",$headquarter->telephone_headquarter,[ "placeholder"=>"Telephone Number", "class"=>"form-control" ]) }}
        {{ $errors->first("telephone_headquarter","<div class='text-red'>:message</div>") }}
    </div>
    <div class="form-group has-feedback">
        {{ Form::email("email_headquarter",$headquarter->email_headquarter,[ "placeholder"=>"Email", "class"=>"form-control", "required" ]) }}
        {{ $errors->first("email_headquarter","<div class='text-red'>:message</div>") }}
    </div>
    <div class="input_fields_wrap">
    </div>
    {{ $errors->first("confirm_user",'<div class="text-green">:message</div>') }}
    {{ Form::hidden("id_company",$headquarter->fk_company) }}
    {{ Form::hidden("id_location",$headquarter->fk_location) }}
    {{ Form::hidden("redirect_link",'acompany') }}
    <br>
</div>
<br>
<div class="col-md-6">
    <button type="submit" class='btn ls-light-blue-btn btn-block'>
        {{trans('messages.act_save')}}
    </button>
</div>
<div class="col-md-6">
    <button type="button" class='btn btn-danger btn-block' onclick="hide_modal_box()">
        {{trans('messages.act_cancel')}}
    </button>
</div>

{{ Form::close() }}

site/app/views/admin/headquarters/show.blade.php
@extends('admin.layouts.default')
@section('dropdown-menu')
    @include('admin.layouts.dropdown-menu')
@stop
@section('sidebar-menu')
    @include('admin.layouts.sidebar-menu')
@stop

@section('content')
    <div class="box box-default">
        <div class="box-header with-border">
            <a href="{{URL::route('headquarters.edit',[ $headquarter->id_headquarter])}}"
               class="btn ls-light-blue-btn btn-flat" title="Edit Headquarter">
                <i class="fa fa-cube"></i>
            </a>
            <h3 class="box-title">Headquarter {{ $headquarter->name_headquarter }} </h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <ul>
                <li> Name: {{ $headquarter->name_headquarter }}  </li>
                <li> Email: {{ $headquarter->email_headquarter }}  </li>
                <li> Telephone: {{ $headquarter->telephone_headquarter }}  </li>
                <li> Address: {{ $headquarter->street}} {{$headquarter->street_nr }},
                    {{ $headquarter->city}}, {{$headquarter->country }}
                </li>
            </ul>
            <h3><i class="fa fa-user"></i> Users</h3>
            <table class="table table-responsive table-bordered">
                <tr>
                    <th>Name</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Groups</th>
                    <th></th>
                </tr>
                @foreach($users as $user)
                    <tr>
                        <td>{{$user->first_name.' '.$user->last_name}} </td>
                        <td>{{$user->username }} </td>
                        <td>{{$user->email }} </td>
                        <td>@foreach($groups as $id_group=> $group)
                                @if($user->fk_group == $id_group)
                                    {{$group}}
                                @endif
                            @endforeach
                        </td>
                        <td>
                            <a href="{{URL::route('members.edit',[$user->id])}}"
                               class="btn ls-light-blue-btn btn-flat" title="Edit user">
                                <i class="fa fa-edit"></i>
                            </a>
                        </td>
                    </tr>
                @endforeach
            </table>
            <br>
            {{ link_to_route('members.create',"Add user",['id'=>$headquarter->id_headquarter],['class'=>"btn ls-light-blue-btn btn-flat "]) }}
        </div>
        <!-- /.box-body -->
    </div>
@stop